SCRIPTS=	bsd_sharp \
		bsd_sharp_releng_2_0 \
		bsd_sharp_releng_2_2 \
		bsd_sharp_releng_2_4 \
		freebsd_texlive_2009 \
		freebsd_texlive_releng_2009 \
		freebsd_texlive_ports \
		freebsd_texlive_ports_marcuscom \
		marcuscom_ports \
		marcuscom_ports_stable \
		ports

SCRIPTSDIR=	${ETCDIR}/portshaker.d

.include <bsd.prog.mk>
